### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by Mhdez221993**
the main.rb file display "hello world!" by executing bin/main.rb
created lib folder
created bin fonder that includes an executable file

### CODE REVIEW

**Review by Berabjesus — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 
Hi @Mhdez221993  and @srizzuto congrats on getting to this part of the curriculum. You have started very well 👍.

### However, there are a few things you need to work on to proceed.

- [ ] It has `lib` directory (with .gitkeep file OR any other **empty** file(s)). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- Currently, you may have a lib folder locally but it's not pushed to the remote repo because it's empty. So, add an empty `.gitkeep` file inside the lib directory and push the change.

- [ ] Remove the `.gitkeep` file in the root folder it's not necessary.

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

**Comment by srizzuto** [comment]
Changes made as required

**Review by Berabjesus — CHANGES_REQUESTED** [review]
## Status: REQUIRED CHANGES 
Hi again @Mhdez221993 and @srizzuto 

#### You must have misunderstood me in the previous review. Please see the requested change below.

- [ ] Create a `lib` folder at the root of the project. (i.e the root folder should have a `lib` folder along with the `bin`... folders). Inside the lib folder create a `.gitkeep` file. Since you **can not** push an empty folder in GitHub the `.gitkeep` file will make sure there is something in it so It can be pushed.
- **Make sure you can see the `lib` folder in the Github repo**

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

**Review by Berabjesus — APPROVED** [review]
# **Status: PROJECT APPROVED** 

#### Excellent job on implementing the changes @Mhdez221993  and @srizzuto. Keep it up.  :champagne: :champagne: 

I wish you all the very best in your next tasks:1st_place_medal:
#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

**Pull request merged**
