### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by Mhdez221993**
We added the logic of the game
Applied DRY principle
covered edges cases (the input from the players is been tested)
The program doesn't allow the perform of invalid action

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Status: Change requested

Good job @Mhdez221993 and @srizzuto for working on the game logic milestone your game is working well so far just a few changes you need to make in order for your project to be approved

## To highlights image

- The game does not allow to move in an occupation position
- The game informs the player about invalid input
- The game informs the user about a winning move(horizontally, vertically, diagonally)

## To improve image

- Code of the project should be divided between classes at least 2 classes minimum but usually, it uses 3(Board, Player, Game) and classes should be kept in the lib folder

## Kindly fix that and submit another CRR 

Regards,

Lydia Ingabire

Slack: Delice Lydia
[Linkedin](https//www.linkedin.com/in/delice-lydia/)
[Twitter](https://twitter.com/IngabireLydia3)

**Comment by srizzuto** [comment]
Changes made as required! @DeliceLydia

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

## Hello Guys

Good job on implementing the changes requested. However, there are some changes that you need to make in order to get your project approved

- [x] Kindly set up the Github actions properly. It's not showing any checks on Github.

- [ ] There is rubocop issues.Kindly fix them.
cc


- [x] You need to close the ```initialize``` function with ```end```. 
The call_variables function is inside ```initialize```

- [ ] No puts/print and gets.chomp outside main.rb file.[screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by enaburekhan — APPROVED** [review]
# Status: Approve:heavy_check_mark:
**Hi team!
Congratulations on this milestone:clap::clap:. Thank you for implementing all the changes requested by the last reviewer:pray:. You can move on with the next milestone:walking:.**


Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Pull request merged**
